SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 700
SCREEN_TITLE = "Dynamic Labyrinth: Chrono Shift Game"

BACKGROUND_COLOR = (20, 20, 30)

PLAYER_SPEED = 5

CAMERA_SMOOTHNESS = 0.12

WORLD_WIDTH = 2000
WORLD_HEIGHT = 1400
CAMERA_LERP = 0.12

DEAD_ZONE_WIDTH_PERCENT = 0.35
DEAD_ZONE_HEIGHT_PERCENT = 0.45
DEAD_ZONE_W = int(SCREEN_WIDTH * DEAD_ZONE_WIDTH_PERCENT)
DEAD_ZONE_H = int(SCREEN_HEIGHT * DEAD_ZONE_HEIGHT_PERCENT)

MAX_LEVEL = 3
MAX_BIG_LEVEL = 2


